Fix: Occasionally this method is being called when this.refs.SlackFeedback is undefined and throws a console error:
TypeError: Cannot read property 'contains' of undefined
  at contains (~/react-slack-feedback/lib/SlackFeedback.js:6:12167)

So lets check if it is defined first.